### PR TITLE
create schedulerHelp function

### LINKED ISSUE #1: Create help function of scheduler
**This function has 2 purposes.
1. Explain to the user what are the commands he can input to the scheduler.
2. Explain to the user what each command does exactly.**

### **Create a function named schedulerHelp in the functions.js file.**

This function will log all the below operations along with explanations:
1. **This operation asks help from the bot to see what ops it can operate.**
**"scheduler 1 help"** ==>  "scheduler" will always come first cos we wanna activate the bot only when it's called.
                                            "1" is the id of the operation. Each op will have an id to be able to identify it.
                                            "help" declares that the user requests the help op from the bot.

2. **This operation iserts or updates user's schedule of the day.**
**"scheduler 2 name insert true/false"** ==> "2" is the id of the op
                                                                          "name" is the name the user will be inserted in the db.
                                                                          "insert" is the op
                                                                          "true/false" indicates if user is free or not for the day.

3. **This operation shows everyones schedule of the day**
 **"scheduler 3 select all"** ==> "3" is the id of the op.
                                                     "select" is the op.
                                                     "all" means show everyones schedule.

4. **This operation shows a specific person's schedule of the day**
 **"scheduler 4 select name"** ==> "4" is the id of the op.
                                                          "select" is the op.
                                                          "name" is the name of the person that the user wants to see the schedule of.

5. **This operation deletes entries of the user in the database**
   **scheduler 5 name delete** ==> "5" is the id of the op.
                                                           "name" is the name of the user.
                                                           "delete" is the op.
   **After this command the user will be prompted for confirmation**
   e.g Are you sure? Press y for yes and n for no

### PR DESCRIPTION
**Pull request by Bill-1991**
close #1

### CODE REVIEW

**Comment by AndreyDmitriev39r** [comment]
Probably worth to rename PR since it will be about slash command making?

I suggest to merge `main` into this branch after #20 will be done. And then proceed with working on this one, when there will be setup to do it with slash commands.

**Comment by Bill-1991** [comment]
This one we won't need anymore i think cos typing / will bring all of the bots commands and eaxh command has a description so we re gonna do the explaining there.
I'm gonna write down the process of creating a command in the documentation.txt, so every issue won't have a ton of information on how to create them.
What do you think?

**Comment by AndreyDmitriev39r** [comment]
> This one we won't need anymore i think cos typing / will bring all of the bots commands and eaxh command has a description so we re gonna do the explaining there. I'm gonna write down the process of creating a command in the documentation.txt, so every issue won't have a ton of information on how to create them. What do you think?

It won't fit in what needs to be done in #21.

We do not need to have command creation guide I think. Even if we do, it should be placed in contributing guide probably.

Issues are tasks, they do not need to have some detailed instructions how to do stuff.

**Comment by Bill-1991** [comment]
#21 will be changed to a features list.
I will be closing this issue.
Descriptions on commands will be described on the issue of each command then

**Comment by Bill-1991** [comment]
Not needed

**Pull request closed without merging**
