### PR TITLE
storeInput function implemented

### LINKED ISSUE #6: Store input
### Create a function named storeInput in the functions.js file.

1) **This function will take as a parameter the `msg.content`.**
    **Then it will split this content by " ".**
    **Finally it will return the splitted content excluding the scheduler string**
    **export the function**

2) **After the above is done head back to bot.js file and assign this function to a variable called input.**

### PR DESCRIPTION
**Pull request by AndreyDmitriev39r**
# Description

Fixes #6

I am not sure if you wanted `msg.content` as a parameter in function definiton. As far as I know, parameter can be called whatever. Clarify if I am wrong.

I need some clarification about env variables and possibly something else to test things on my end properly, wrote about that in discord, clarify there please.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Bill-1991** [comment]
2 things i wanna mention.

first thing i think it's better to put the input variable inside bot's functionality right after if ( msg,content === "" ), 
cos the code will show by itself how it functions by the end.

second, i think you have to pass msg.content as the parameter of functions.storeInput cos i don't think it will work otherwise.

**Comment by AndreyDmitriev39r** [comment]
> first thing i think it's better to put the input variable inside bot's functionality right after if ( msg,channel.id === "" ), cos the code will show by itself how it functions by the end.

Do you mean after if block. Or inside if block. Specify.

**Comment by AndreyDmitriev39r** [comment]
> second, i think you have to pass msg.content as the parameter of functions.storeInput cos i don't think it will work otherwise.

Why? If function imported to bot.js, it will some function which can consule any string. Suggest any testing to check it?

**Comment by Bill-1991** [comment]
Inside.
Ok let me check the second one, cos i'm not sure either.

**Review by Bill-1991 — APPROVED** [review]
Cool!

**Pull request merged**
