### PR TITLE
Setup for commands

### LINKED ISSUE #19: Prepare codebase for slash commands implementation.
Create `commands` folder.
In that folder, make `ping.js` file and implement the most basic ping command in order to test functionality, which will be described in the below.

In the main file, implement:

1. Loading command files. The example: https://discordjs.guide/creating-your-bot/command-handling.html#loading-command-files
2. Receiving command interactions. https://discordjs.guide/creating-your-bot/command-handling.html#receiving-command-interactions
3. Executing commands. https://discordjs.guide/creating-your-bot/command-handling.html#executing-commands
4. Commands registration https://discordjs.guide/creating-your-bot/command-deployment.html#guild-commands

### PR DESCRIPTION
**Pull request by AndreyDmitriev39r**
# Description

Fixes #19

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore items (this includes basic clean up of files, or updates to packages)
- [ ] Updates to documentation

## Checklist

- [x] I have a descriptive title for my PR
- [x] I have linked this PR to the corresponding issue. [See how to do that here.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] I have run the project locally and reviewed the code changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Bill-1991 — APPROVED** [review]
Cool...one mention that it doesn't matter if we implement or not right now.
Maybe we will just move events in a separate folder as instructed by docs.
If we decide to expand on the bot sometime in the future it's better to keep all events in a separate folder.
Tel me if you want to do it that way, otherwise we re merging it right now

**Comment by AndreyDmitriev39r** [comment]
> Cool...one mention that it doesn't matter if we implement or not right now. Maybe we will just move events in a separate folder as instructed by docs. If we decide to expand on the bot sometime in the future it's better to keep all events in a separate folder. Tel me if you want to do it that way, otherwise we re merging it right now

Give me reference to the documentation you are referring to please.

**Comment by Bill-1991** [comment]
https://discordjs.guide/creating-your-bot/event-handling.html#individual-event-files

**Comment by AndreyDmitriev39r** [comment]
got it, will do

**Review by Bill-1991 — APPROVED** [review]
cool

**Pull request merged**
